name: build

on:
  push:
  pull_request:
  workflow_run:
    workflows:
      - scheduled
    branches:
      - main
    types:
      - requested

jobs:
  Emscripten:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          wget -q https://github.com/emscripten-core/emsdk/archive/master.tar.gz
          tar -xvf master.tar.gz
          emsdk-master/emsdk update
          emsdk-master/emsdk install latest
          emsdk-master/emsdk activate latest
          
          wget -q https://github.com/ocornut/imgui/archive/refs/tags/v1.88.tar.gz
          tar -xvf v1.88.tar.gz

      - name: Build example_emscripten_opengl3
        run: |
          pushd emsdk-master
          source ./emsdk_env.sh
          popd
          pushd imgui-1.88
          make -C examples/example_emscripten_opengl3
